server.port:
  8081

spring:
  application:
    name: moderation-service
  datasource:
    username: sa
    url: jdbc:h2:file:~/algacomments-moderation-service-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driver-class-name: org.h2.Driver
    password: '123'
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'